<div class="row">
	<div class="span12">
		<h1>Enhance online customer engagement</h1>
	</div>
</div>
<div class="row">
	<div class="span5 offset1">
		<div class="hero-unit">
			<h2>Secure Twitter account-sharing.</h2>
			<p>Enable your team to tweet on your behalf, manage your brand, and
				provide excellent service to your customers. Never give away your
				twitter password.

		</div>
	</div>
	<div class="span4">
		<h2>By signing up you get:</h2>
		<ul>
			<li>The ability to schedule/delay tweets</li>
			<li>Other individuals can manage your corporate twitter account
				without needing your password.</li>
			<li>And lots more!</li>


		</ul>
	</div>
</div>

<div class="row">
	<div class="span4"></div>
	<div class="span4"></div>
	<div class="span4"></div>
</div>