<div class="row">
	<div class="span12">
		<div class="social_channel_block">
			<ul>
				<li><a href=""><img src="" alt="account #1" /></a></li>
				<li><a href=""><img src="" alt="account #2" /></a></li>
			</ul>
		</div>
	</div>
</div>
<div class="row">
	<div class="span7">
		<div class="social_channel_tabs">
			<ul>
				<li><a href="#social_channel_tabs_timeline">Timeline</a></li>
				<li><a href="#social_channel_tabs_DMs">Direct Messages</a></li>
			</ul>
			<div id="social_channel_tabs_timeline">
			<?php
if (isset($this->tweets)) {
    echo $this->partial('partials/tweet_block.phtml',
            array(
                    'tweets' => $this->tweets
            ));
} else {
    echo "no tweets to display,";
}
?>
			</div>
			<div id="social_channel_tabs_DMs"></div>
		</div>
		<script type="text/javascript">
		$(document).ready(function () {
			$(".social_channel_tabs").wijtabs();
		});
</script>
	</div>
	<div class="span5">
		<div class="detail">Detailed information goes here about the selected
			person, message, or whatever.</div>
		<hr />
		<div class="profile">Profile stats here about the person that said
			whatever was said. If they were</div>
	</div>
</div>